main/urls.py
from django.urls import path

from . import views


app_name='main'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

product/urls.py
from django.urls import path

from . import views


app_name='product'
urlpatterns = [
    path('<str:category>/', views.CategorySubList.as_view(), name='category'),
    path('<str:category>/<str:sub>/', views.ProductList.as_view(), name='product-list'),
    path('<str:category>/<str:sub>/<str:code>/', views.ProductDetail.as_view(), name='product-detail'),
]

wellbos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('products/', include('product.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/models.py
# import inflect

from product.utils import unique_product_code
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.urls import reverse

from PIL import Image
from io import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile
import os
import magic

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=30, unique=True, blank=True)
    
    def save(self):
        """Save method for Category."""
        self.slug = self.name.lower().replace(' ', '-')

        self.save()
    
    # Override save method to update slug
    def save(self, *args, **kwargs):
        if self.name:
            self.slug = self.name.lower().replace(' ', '-')
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Return absolute url for Category."""
        return reverse('product:category', kwargs={'category': self.slug})
    

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=30, unique=True, blank=True)
    parent = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='product/category/sub', blank=True)
    desc = models.CharField(max_length=30, default="Trustworthy threads")
    description = models.TextField(default="From dress-down Fridays to weekend 'fits, our edit of men’s polo shirts knows no bounds when it comes to versatility. From long-sleeve polo shirts to short-sleeve polo tops, Wellbos DESIGN has hundreds of styles and designs to suit your unique style, or take your pick from men's designer polo shirts by Fred Perry and Polo Ralph Lauren, adding their classic logos to your smart-casual rotation. You can pair your polo T-shirt with skinny jeans, tailored shorts or even check trousers. Preppy vibes incoming.")

    def __str__(self):
        return self.name

    def save(self):
        """Save method for Category."""
        self.slug = self.name.lower().replace(' ', '-')

        self.save()
    
    # Override save method to update slug
    def save(self, *args, **kwargs):
        if self.name:
            self.slug = self.name.lower().replace(' ', '-')
        super().save(*args, **kwargs)
    class Meta:
        verbose_name = 'Sub-Category'
        verbose_name_plural = 'Sub-Categories'


class ProductImage(models.Model):
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE)

    image = models.ImageField(upload_to='product/images',max_length=500,blank=True,null=True)
    thumbnail = models.ImageField(upload_to='product/images/thumbs',max_length=500,blank=True,null=True)

    def create_thumbnail(self):
        # original code for this method came from
        # http://snipt.net/danfreak/generate-thumbnails-in-django-with-pil/

        # If there is no image associated with this.
        # do not create thumbnail
        if not self.image:
            return

        # Set our max thumbnail size in a tuple (max width, max height)
        THUMBNAIL_SIZE = (200,200)

        print(magic.from_buffer(self.image.file.read(2048), mime=True))
        print(dir(self.image.file))
        print(dir(self.image))

        DJANGO_TYPE = self.image.file.content_type

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'

        # Open original photo which we want to thumbnail using PIL's Image
        image = Image.open(StringIO(self.image.file.read()).decode("utf-8"))

        # We use our PIL Image object to create the thumbnail, which already
        # has a thumbnail() convenience method that contrains proportions.
        # Additionally, we use Image.ANTIALIAS to make the image look better.
        # Without antialiasing the image pattern artifacts may result.
        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        # Save the thumbnail
        temp_handle = StringIO()
        image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)

        # Save image to a SimpleUploadedFile which can be saved into
        # ImageField
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                temp_handle.read(), content_type=DJANGO_TYPE)
        # Save SimpleUploadedFile into image field
        self.thumbnail.save('%s_thumbnail.%s'%(os.path.splitext(suf.name)[0],FILE_EXTENSION), suf, save=False)

    def save(self):
        # create a thumbnail
        self.create_thumbnail()

        super().save()
    
    def __str__(self):
        return self.product.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField(default=0.0)
    color = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, null=True)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.DO_NOTHING, null=True)
    brand_desc = models.TextField(default='This is WELLBOS DESIGN – your go-to for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to WELLBOS, our universal brand is here for you, and comes in Plus and Tall. Created by us, styled by you.')
    code = models.CharField(max_length=10, unique=True, editable=False)
    details = models.TextField()
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    models_height = models.CharField(max_length=15, blank=True)
    models_wearing = models.CharField(max_length=15, blank=True)

    def image_count(self):
        return self.productimage_set.count()
    
    def get_image(self):
        image = self.productimage_set.first()
        return image
    
    # THis gets the details in a list format
    def list_details(self):
        return [i.strip().capitalize() for i in self.details.split(',')]

    def __str__(self):
        return self.name

class ProductReview(models.Model):
    stars = models.IntegerField(default=1)
    comment = models.TextField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey('account.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name



# Signals
@receiver(pre_save, sender = Product)
def create_product_code(sender, instance, **kwargs):
    if bool(instance.code) == False:
        # Create a unique product code
        code = unique_product_code(instance)
        instance.code = code
        instance.save()

product/views.py
from django.http.response import Http404
from product.mixins import ParseKwargs
from product.models import Category, Product, SubCategory
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView, ListView


class CategorySubList(TemplateView):
    template_name = 'product/category-sub-list.html'
    extra_context = {
        'title': ''
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the category
        category = self.kwargs.get('category')
        category = get_object_or_404(Category, slug__exact=category)
        context["title"] = category.name.capitalize()
        context["category"] = category.slug

        # Get the sublist
        context['sublist'] = category.subcategory_set.all()

        return context
    
class ProductList(ListView, ParseKwargs):
    template_name = 'product/product-list.html'
    extra_context = {
    }
    model = Product

    def custom_queryset(self, category, sub_category):
        return Product.objects.filter(category=category, sub_category=sub_category)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Identify the page
        category, sub_category = self.parse_link()

        context["title"] = f"{category.name.capitalize()}\'s {sub_category.name.capitalize()}"

        # Get the products with the category and sub category
        queryset = self.custom_queryset(category, sub_category)
        context["products"] = queryset
        context["total_count"] = queryset.count()
        context["category"] = category
        context["sub_category"] = sub_category

        return context


class ProductDetail(TemplateView, ParseKwargs):
    template_name = 'product/product-detail.html'
    extra_context = {
    }
    model = Product

    def get_object(self):
        category, sub_category = self.parse_link()
        queryset = Product.objects.filter(category=category, sub_category=sub_category)
        # Get the product in the above query set or return 404
        try:
            return queryset.get(code=self.kwargs.get('code'))
        except Product.DoesNotExist:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the product
        product = self.get_object()

        context["title"] = product.name.capitalize()
        context['product'] = product

        return context
    

product/templates/product/category-sub-list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<section class="sub-categories my-5">
    <div class="container-fluid">
        <h3 class="my-2 text-center mb-5">{{ title }} wears</h3>
        <div class="row justify-content-center mt-4">
            {% for i in sublist %}
            <div class="col-sm-4 text-center">
                <a href="{% url 'product:product-list' category i.slug %}">
                    <img src="{{ i.image.url }}" alt="" class="img-fluid">
                    <h5 class="mt-2">{{ i.name.upper }}</h5>
                    <p>{{ i.desc }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

product/templates/product/product-detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

    <section class="breadcrumbs">
      <div class="container-fluid">
        <a href="#"><span>Home</span> &raquo;</a>
        <a href="#"><span>Home</span> &raquo;</a>
        <a href="#"><span>Home</span> &raquo;</a>
        <a href="#"><span>Home</span> &raquo;</a>
        <a href="#" class="active">{{ product.name }}</a>
      </div>
    </section>

    <section class="main-product">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8 product-images">
            <div class="product-dot">
              <img src="{% static 'images/pickle/first-2.webp' %}" alt="">
              <img src="{% static 'images/pickle/second-2.webp' %}" alt="">
              <img src="{% static 'images/pickle/third-2.webp' %}" alt="">
              <img src="{% static 'images/pickle/fourth-2.webp' %}" alt="">
            </div>
            <div class="products-pics-box">
              <div class="products-pics owl-carousel">
                <div class="boxing">
                  <img src="{% static 'images/pickle/first-1.webp' %}" alt="">
                </div>
                <div class="boxing">
                  <img src="{% static 'images/pickle/second-1.webp' %}" alt="">
                </div>
                <div class="boxing">
                  <img src="{% static 'images/pickle/third-1.webp' %}" alt="">
                </div>
                <div class="boxing">
                  <img src="{% static 'images/pickle/fourth-1.webp' %}" alt="">
                </div>
              </div>
              <div class="products-pics-nav">
                <img src="{% static 'fonts/svg/arrow-left.svg' %}" alt="">
                <img src="{% static 'fonts/svg/arrow-right.svg' %}" alt="">
              </div>
            </div>
          </div>
          <div class="col-12 col-sm-8 col-md-4 product-mini-desc">
            <div class="top">
              <h5>{{ product.name }}</h5>
              <p class="price">£{{ product.price }}</p>

              <p class="desc-type mt-5"><span>colour:</span><span>{{ product.color }}</span></p>
              <p class="desc-type"><span>size:</span><a href="#">Find your fit assistant size</a></p>
              <select>
                <option>Please Select</option>
                <option>W28 L32</option>
                <option>W28 L32</option>
                <option>W28 L32</option>
                <option>W28 L32</option>
                <option>W28 L32</option>
                <option>W28 L32</option>
              </select>
              <div class="cart-btn-box">
                <a href="#" class="btn btn-success filled">Add to bag</a>
                <span><img src="{% static 'fonts/svg/heart.svg' %}" alt=""></span>
              </div>
            </div>
            
            <!-- <div class="bottom">
              <p class="head">Sizing help</p>
              <p>Still unsure what size to get?</p>
              <a href="#">Find your recommended size</a>
            </div> -->
          </div>
        </div>
      </div>
    </section>

    <section class="product-description active">
      <div class="container-fluid">
        <div class="row boxes">
          <div class="col-md-4 single-box">
            <h5>Product details</h5>
            <p><a href="#">Jeans</a> by <a href="#">WELLBOS DESIGN</a></p>
            <ul>
                {% for i in product.list_details %}
                    <li>{{i}}</li>
                {% endfor %}
            </ul>
          </div>
          <div class="col-md-4 single-box">
            <h5>PRODUCT CODE</h5>
            <p>{{ product.code }}</p>

            <h5 class="mt-4">Brand</h5>
            <p>This is WELLBOS DESIGN – your go-to for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to WELLBOS, our universal brand is here for you, and comes in Plus and Tall. Created by us, styled by you.</p>
          </div>
          <div class="col-md-4 single-box">
            <h5>SIZE & FIT</h5>

            <p class="mt-3">Model's height: 188cm/6'2" <br> Model is wearing: W 32" L 32"</p>
            <p>The inseam on these jeans measures 71cm. They’re a little shorter than normal</p>

            <h5 class="mt-4">LOOK AFTER ME</h5>
            <p>Machine wash according to instructions on care label</p>

            <h5 class="mt-4">About me</h5>
            <p>Non-stretch denim</p>
            <p>We are a proud member of The Better Cotton Initiative. Better Cotton is sourced via a system of Mass Balance</p>
            <p>Main: 100% Cotton.</p>
          </div>
        </div>
      </div>
    </section>

    <section class='show-more'>
      <div class="container-fluid py-5 text-center">
        <a href="#" class="btn px-5">show more</a>
      </div>
    </section>

    <!-- <section id="reviews">
      <div class="container-fluid">
        <div class="review-boxes">
          <div class="review-box">
            <h4>Review</h4>
            <div class="star-box">
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="value">3.8 (33 Reviews)</span>
            </div>
            <p>75% of customers recommend this product</p>

            <h4>CUSTOMER RATING</h4>
            <div class="rating-box">
              <p class="head"><span><i class="fas fa-user"></i></span> Fit:</p>
              <span class="rating"></span>
              <p class="bottom">
                <span>Runs small</span>
                <span>Runs large</span>
              </p>
            </div>
            <div class="rating-box">
              <p class="head"><span><i class="fas fa-user"></i></span> Fit:</p>
              <span class="rating"></span>
              <p class="bottom">
                <span>Runs small</span>
                <span>Runs large</span>
              </p>
            </div>
          </div>
          <div class="review-box">
            <h5>Review</h5>
            <div class="star-box">
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <span class="star"><i class="fas fa-star"></i></span>
              <small class="value">1 month ago</small>
            </div>
            <small>Verified Purchaser</small>

          </div>
        </div>
      </div>
    </section> -->

{% endblock content %}

product/templates/product/product-list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="product-listing jumbotron">
    <div class="container-fluid">
        <h1>{{ title }} Shirts</h1>
        <p>{{ sub_category.description }}</p>
        <p class="redux">View less</p>
    </div>
</div>

<div class="top-tiny">
    <div class="container-fluid">
        <a href="#" class="circular">long sleeve polos</a>
    </div>
</div>

<section class="filter">
    <div class="container-fluid">
        <form action="">
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
            <select name="" id="">
                <option value="">Price</option>
            </select>
        </form>
    </div>
</section>

<div class="top-tiny">
    <div class="container-fluid">
        <p>{{total_count}} styles found</a>
    </div>
</div>


<section class="products">
    <div class="container-fluid">
        <div class="products-list">
            {% for i in products %}
                <a href="{% url 'product:product-detail' category.slug sub_category.slug i.code %}" class="product-box">
                    <div class="head">
                        <img src="{{ i.get_image.image.url }}" alt="">
                        <span class="icon"><img  src="{% static 'fonts/svg/heart.svg' %}" alt=""></span>
                    </div>
                    <div class="bottom">
                        <p class="desc">{{ i.name }}</p>
                        <p class="price">£ {{i.price}}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</section>

<section>
    <div class="container-fluid py-5">
        <div class="product-loader">
            <p>You've viewed {{ products.count }} of {{ total_count }} products</p>
            <progress value="70" max="100">70 %</progress>
            <a href="#" class="btn">Load more</a>
        </div>
    </div>
</section>
{% endblock content %}