main/urls.py
from django.urls import path

from . import views


app_name='main'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

wellbos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('products/', include('product.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from product.models import Category
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'title': 'Buy your clothes and brands'
    }
    

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

    {% include "main/head.html" %}

    <body>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{message}}
            </div>
            {% endfor %}
        {% endif %}

        {% include "main/desktop_navbar.html" %}

        {% include "main/mobile_bar.html" %}

        {% include "main/mobile_nav.html" %}

        {% block content %}
          
        {% endblock content %}

        <section class="social-but">
            <div class="container-fluid">
                <a href="#"><img src="{% static 'fonts/svg/facebook.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'fonts/svg/instagram.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'fonts/svg/twitter.svg' %}" alt=""></a>
                <a class='noona'><img src="{% static 'fonts/svg/bank.svg' %}" alt=""></a>
                <a><img src="{% static 'fonts/svg/bank.svg' %}" alt=""></a>
                <a><img src="{% static 'fonts/svg/bank.svg' %}" alt=""></a>
                <a><img src="{% static 'fonts/svg/bank.svg' %}" alt=""></a>
                <a><img src="{% static 'fonts/svg/bank.svg' %}" alt=""></a>
            </div>
        </section>

        <section class="footer">
            <div class="container-fluid">
                <div class="row py-3">
                    <div class="col-sm-3">
                        <h5>HELP & INFORMATION</h5>
                        <ul>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <h5>about wellbos</h5>
                        <ul>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <h5>more form wellbos</h5>
                        <ul>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 1</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <h5>shopping from:</h5>
                        <ul>
                            <a href="#">You are in Mumbai</a>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <section class="credit">
            <div class="container-fluid">
                <p>© 2021 WELLBOS</p>
                <p class="links">
                    <a href="#">Privacy & Cookies</a>
                    <a href="#">Ts&Cs</a>
                    <a href="#">Accessibility</a>
                </p>
            </div>
        </section>

    
        {% include "main/scripts.html" %}
    </body>

</html>

main/templates/main/desktop_navbar.html
{% load static %}
{% load wellbostags %}
<nav id="desktop-nav">
    <div class="container-fluid">
        <div class="navbar">
            <a href="{% url 'main:home' %}" class="navbar-brand">
                <img src="{% static 'images/logo1.png' %}" alt="" class="img-fluid">
            </a>

            <div id="desktop_nav">
                {% get_category as v %}
                {% for i in v %}
                    <div class='nav_box men'>
                        <a href="{{ i.get_absolute_url }}" class="nav_link">{{i.name}}</a>
                        <div class="nav_backdrop">
                            <div class="dropdown_container">
                                <div class="dropdown">
                                    <ul>
                                        <li class="special"><a href="#">Indian & Fusion Wear</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>

                                        <hr>
                                        <li class="special"><a href="#">Belts, Scarves & More</a></li>
                                        <li class="special"><a href="#">Watches & Wearables</a></li>
                                    </ul>
                                    <ul>
                                        <li class="special"><a href="#">Indian & Fusion Wear</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>

                                        <hr>
                                        <li class="special"><a href="#">Belts, Scarves & More</a></li>
                                        <li class="special"><a href="#">Watches & Wearables</a></li>
                                    </ul>
                                    <ul>
                                        <li class="special"><a href="#">Indian & Fusion Wear</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>

                                        <hr>
                                        <li class="special"><a href="#">Belts, Scarves & More</a></li>
                                        <li class="special"><a href="#">Watches & Wearables</a></li>
                                    </ul>
                                    <ul>
                                        <li class="special"><a href="#">Indian & Fusion Wear</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>

                                        <hr>
                                        <li class="special"><a href="#">Belts, Scarves & More</a></li>
                                        <li class="special"><a href="#">Watches & Wearables</a></li>
                                    </ul>
                                    <ul>
                                        <li class="special"><a href="#">Indian & Fusion Wear</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>
                                        <li><a href="#">Test 1</a></li>

                                        <hr>
                                        <li class="special"><a href="#">Belts, Scarves & More</a></li>
                                        <li class="special"><a href="#">Watches & Wearables</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>


            <div class="nav_search">
                <form action="">
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1">
                            <img src="{% static 'fonts/svg/search.svg' %}" alt="">
                        </span>
                        <input type="text" class="form-control" placeholder="Search for products, brands and more" aria-label="Search" aria-describedby="basic-addon1">
                    </div>
                </form>
            </div>

            <div id="nav_icons">
                <a href="#">
                    <img src="{% static 'fonts/svg/person.svg' %}" alt="">
                    <p>Profile</p>
                </a>
                <a href="#">
                    <img src="{% static 'fonts/svg/heart.svg' %}" alt="">
                    <p>Wishlist</p>
                </a>
                <a href="#">
                    <img src="{% static 'fonts/svg/bag.svg' %}" alt="">
                    <p>Bag</p>
                </a>
            </div>
        </div>
    </div>
</nav>

main/templates/main/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <!-- <meta name="Keywords" content="KEYWORDS HERE (SEPERATE WITH COMMA)" lang="en" xml:lang="en"> -->
    <!-- <meta name="Description" content="DESCRIPTION HERE" lang="en" xml:lang="en"> -->
    <meta name="viewport" id="myViewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="">

    {% if title %}
    <title>Wellbos: {{ title }}</title>
    {% else %}
    <title>Wellbos</title>
    {% endif %}
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.njs"></script> -->

    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> -->
</head>

main/templates/main/mobile_bar.html
{% load static %}
<div id="mobile-bar" class="navbar">
    <button id='ham'>
        <img src="{% static 'fonts/svg/list.svg' %}" alt="">
    </button>
    <a href="{% url 'main:home' %}" class="brand">Wellbos</a>
    <div class="top-icons">
        <a href="#"><img src="{% static 'fonts/svg/search.svg' %}" alt=""></a>
        <a href="#"><img src="{% static 'fonts/svg/heart.svg' %}" alt=""></a>
        <a href="#"><img src="{% static 'fonts/svg/bag.svg' %}" alt=""></a>
    </div>
</div>

<nav id="mobile-nav" class="nav-drill">
    <ul class="nav-items nav-level-1">
        <li class="nav-item nav-expand">
            <a class="nav-link nav-expand-link" href="#">
                Menu
            </a>
            <ul class="nav-items nav-expand-content">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Level 2
                    </a>
                </li>
                <li class="nav-item nav-expand">
                    <a class="nav-link nav-expand-link" href="#">
                        Menu
                    </a>
                    <ul class="nav-items nav-expand-content">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Level 3
                            </a>
                        </li>
                        <li class="nav-item nav-expand">
                            <a class="nav-link nav-expand-link" href="#">
                                Menu
                            </a>
                            <ul class="nav-items nav-expand-content">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Level 4
                                    </a>
                                </li>
                                <li class="nav-item nav-expand">
                                    <a class="nav-link nav-expand-link" href="#">
                                        Menu
                                    </a>
                                    <ul class="nav-items nav-expand-content">
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                Level 5 Directory
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                Level 5 Contact
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                Level 5 Quick links
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                Level 5 Launchpad
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Level 4 Directory
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Level 4 Contact
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Level 4 Quick links
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Level 4 Launchpad
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Level 3 Directory
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Level 3 Contact
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Level 3 Quick links
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Level 3 Launchpad
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Level 2 Directory
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Level 2 Contact
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Level 2 Quick links
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Level 2 Launchpad
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                Directory
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                Contact
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                Quick links
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                Launchpad
            </a>
        </li>
    </ul>
</nav>

main/templates/main/scripts.html
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>